services:
  - type: web
    name: frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    staticPublish: frontend/dist
    envVars:
      - key: CLIENT_PORT
        value: 8080
      - key: VITE_API_URL
        value: https://your-backend-service.onrender.com

  - type: web
    name: backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: API_PORT
        value: 5000